import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({data}) {

    console.log(data);
    const posts=[...data.posts]
    // console.log(typeof (data.posts));
    // console.log( [...data.posts]);

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/*<div>*/}
        {/*    {posts.map((post,index)=>{*/}
        {/*        <p key={post.id}>*/}
        {/*            {post.title}*/}
        {/*        </p>*/}
        {/*    })}*/}

        {/*</div>*/}
        {/*<ul>*/}


        {posts.map(((value, index) => {

            return (<p key={index}>

                <Image src={value.feature_image} width={100} height={100}/>
                <Link href={`/post/${value.id}`} >
                {value.title}
                </Link>
            </p>)
        }))}

        {/*</ul>*/}




    </div>
  )
}


// export async function getStaticProps() {
export async function getServerSideProps() {
    console.log(`test`);
    // Get external data from the file system, API, DB, etc.
    const res =await fetch(`http://localhost:2368/ghost/api/v3/content/posts/?key=cb015349fc50d1e5ccf1e7e1a8`)
    const data=await res.json()
    console.log("data",data);



    // The value of the `props` key will be
    //  passed to the `Home` component
    return {
        props: {data}
    }
}
